import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import '@mantine/notifications/styles.css';
import '@mantine/core/styles.css';

import "./globals.css";
import Script from "next/script";
import Footer from "../../Components/Footer";
import LayNav from "../../Components/LayNav";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        <Script async src="/js/jquery-3.6.1.min.js" />
        <MantineProvider>
        <Notifications />
        <LayNav/>
        {children}
        <Footer/>
        </MantineProvider>

        <Script src="/bootstrap.js" />
      </body>
    </html>
  );
}
